# Site settings
title: "Bilah Ahmed Satti - Database Developer Portfolio"
description: "A portfolio showcasing my database development projects, skills, and experience."


# Theme settings
theme: jekyll-theme-cayman # You can choose another theme if you prefer


