# Site settings
title: "Bilah Ahmed Satti - Database Developer Portfolio"
description: "A portfolio showcasing my database development projects, skills, and experience."


# Theme settings
theme: jekyll-theme-cayman # You can choose another theme if you prefer

# Build settings
markdown: kramdown
highlighter: rouge

# Custom settings
permalink: pretty
paginate: 5

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives

# Social links (for the header or footer)
social_links:
  - name: GitHub
    url: "https://github.com/[your-username]"
    icon: "fab fa-github"
  - name: LinkedIn
    url: "https://linkedin.com/in/[your-linkedin-profile]"
    icon: "fab fa-linkedin"
  - name: Email
    url: "mailto:[your-email]"
    icon: "fas fa-envelope"

# Navigation menu
navigation:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/projects"
  - title: "Skills"
    url: "/skills"
  - title: "Certifications"
    url: "/certifications"
  - title: "Contact"
    url: "/contact"

# SEO settings
jekyll_seo_tag:
  title: "[Your Name] - Database Developer"
  description: "Portfolio showcasing database development skills, projects, and professional experience."
 

# Sitemap settings
sitemap:
  changefreq: weekly
  priority: 0.7
  exclude:
    - "/404.html"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - vendor/bundle
  - vendor/cache
  - vendor/gems
  - vendor/ruby

# Pagination settings
paginate_path: "/page:num"

# Default settings for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Bilal Satti"

